
# Netlify configuration
[build]
  command = "npm run build"
  publish = "dist"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables
[build.environment]
  NODE_VERSION = "20"
  NETLIFY_SKIP_ANGULAR_PLUGIN = "true"
